name: dictionary
description: A simple flutter vocabulary database featuring sqlite and provider state management.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  intl: any
  path: any
  path_provider: any
  provider: any
  sqflite: any
  sqflite_common_ffi: any
  collection: ^1.15.0-nullsafety.4
  url_launcher: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

